// 鶴舞カントリー倶楽部 競技規則データ
const CLUB_RULES_DATA = {
  categories: [
    {
      id: "competition",
      icon: "📋",
      title: "競技規則",
      items: [
        {
          title: "競技委員会の権限",
          content: "競技委員会は鶴舞カントリー倶楽部に於いて競技の条件を修正する権限を有し、すべての事柄について競技委員会の裁定は最終である。\n\n<div class='club-rule-sub'>1.</div>\nイ．競技は特に定められた場合を除き、すべて倶楽部所定のハンディキャップ(以下HDCPという)のもとに実施する。\nロ．競技参加資格はHDCPを有し、満20才以上の社会人であることとする。\n\n<div class='club-rule-sub'>2.</div>\n他の所属倶楽部のHDCPに変動があった場合は、直ちにハンディキャップ委員会に申告しなければならない。これを怠れば競技に失格する。"
        },
        {
          title: "HDCP区分と使用ティー",
          content: "<div class='club-rule-sub'>3. 競技区分及び競技使用ティーイングエリア（以下TAという)は次の通りとする。</div>\n\n<div class='club-rule-sub'>イ．HDCP別区分</div>\n<ul>\n<li>Aクラス：13以下</li>\n<li>Bクラス：14以上</li>\n<li>オープン：HDCP取得者</li>\n</ul>\n\n<div class='club-rule-sub'>ロ．月例杯オープンの使用ティについて</div>\n<ul>\n<li>第一ブロックは男性「RT」女性「FT」</li>\n<li>第二ブロックは男性「BT」女性「RT」とする。</li>\n</ul>\n\n<div class='club-rule-sub'>ハ．競技別使用TAと女子HDCP</div>\n<table class='club-rule-table'>\n<thead><tr><th>競技名</th><th>男子使用TA</th><th>女子使用TA</th><th>女子HDCP</th></tr></thead>\n<tbody>\n<tr><td>スクラッチ競技</td><td>バック</td><td>バック</td><td></td></tr>\n<tr><td>クラブ選手権</td><td>バック</td><td>バック</td><td></td></tr>\n<tr><td>キャプテン杯</td><td>バック</td><td>レギュラー</td><td>HD+3</td></tr>\n<tr><td>理事長杯</td><td>バック</td><td>バック</td><td>HD+6</td></tr>\n<tr><td>シニア選手権</td><td>レギュラー</td><td>レギュラー</td><td></td></tr>\n<tr><td>ミッドシニア杯</td><td>レギュラー</td><td>フロント</td><td>HD+2</td></tr>\n<tr><td>グランドシニア杯</td><td>レギュラー</td><td>レギュラー</td><td></td></tr>\n<tr><td>月例杯A</td><td>バック</td><td>レギュラー</td><td>HD+3</td></tr>\n<tr><td>月例杯B</td><td>レギュラー</td><td>フロント</td><td>HD+2</td></tr>\n<tr><td>月例杯オープン①</td><td>レギュラー</td><td>フロント</td><td>HD+2</td></tr>\n<tr><td>月例杯オープン②</td><td>バック</td><td>レギュラー</td><td>HD+3</td></tr>\n<tr><td>上記以外の競技</td><td>レギュラー</td><td>フロント</td><td>HD+2</td></tr>\n</tbody>\n</table>\n\n競技のHDCP上限は男子30とし女子は35とする。"
        },
        {
          title: "競技一覧表",
          content: "<div class='club-rule-sub'>5. ハ．競技でタイとなった場合、順位は下表の通りとする。</div>\n\n<table class='club-rule-table'>\n<thead><tr><th>競技名</th><th>予選 競技方法</th><th>予選 タイの場合</th><th>決勝 競技方法</th><th>決勝 タイの場合</th></tr></thead>\n<tbody>\n<tr><td>スクラッチ競技</td><td>36Hストローク戦（スクラッチ）</td><td>マッチング</td><td>36Hストローク戦（スクラッチ）</td><td>エキストラ</td></tr>\n<tr><td>クラブ選手権</td><td>36Hストローク戦（スクラッチ）</td><td>マッチング</td><td>36Hマッチ戦（スクラッチ）</td><td>エキストラ</td></tr>\n<tr><td>キャプテン杯</td><td>18Hストローク戦（ハンデ）</td><td>マッチング</td><td>18Hストローク戦（ハンデ）</td><td>マッチング</td></tr>\n<tr><td>理事長杯</td><td>18Hストローク戦（ハンデ）</td><td>マッチング</td><td>36Hマッチ戦（ハンデ）</td><td>エキストラ</td></tr>\n<tr><td>シニア選手権</td><td>18Hストローク戦（スクラッチ）</td><td>マッチング</td><td>27Hマッチ戦（スクラッチ）</td><td>エキストラ</td></tr>\n<tr><td>ミッドシニア杯</td><td>18Hストローク戦（ハンデ）</td><td>マッチング</td><td>18Hストローク戦（ハンデ）</td><td>マッチング</td></tr>\n<tr><td>グランドシニア杯</td><td>18Hストローク戦（スクラッチ）</td><td>マッチング</td><td>18Hマッチ戦（スクラッチ）</td><td>エキストラ</td></tr>\n<tr><td>月例杯A・B・オープン</td><td></td><td></td><td>ストローク戦</td><td>マッチング</td></tr>\n<tr><td>上記以外の競技</td><td></td><td></td><td>競技による</td><td>マッチング</td></tr>\n</tbody>\n</table>\n\n※ クラブ選手権は予選競技を2週で行う。\n第1ラウンドでストローク89以下、上位32名が第2ラウンドに進出できる。\n第1ラウンドと第2ラウンドの合計で上位16名が決勝進出。\n\n※ 2ラウンド以上の競技の場合は最終ラウンドのスコアにより決定。\nマッチングスコアカード方式:インコースの合計スコアにより決定。\n同スコアの場合は13〜18番の6ホールのスコアにより決定。さらに同スコアの場合は16〜18番の3ホールのスコアにより決定。それでも同スコアの場合は18番ホールからのカウントバック方式により決定。"
        },
        {
          title: "参加条件・競技資格",
          content: "<div class='club-rule-sub'>4.</div>\n競技参加者が16名(グランドシニア杯、平日競技は12名）に達しない場合は競技不成立とする。但し競技委員が認めた場合はこの限りではない。\n\n<div class='club-rule-sub'>8. 下記の競技参加資格は次の通りである。</div>\n<ul>\n<li>クラブ選手権：HDCP 10まで</li>\n<li>シニア選手権：HDCP 24まで（男子は本年中に55才以上、女子は本年中に50才以上に到達の者※KGAの年令規定に準ずる）</li>\n<li>理事長杯：HDCP 24まで</li>\n<li>キャプテン杯：HDCP 24まで</li>\n<li>スクラッチ競技：HDCP 10まで</li>\n<li>ミッドシニア杯：本年中に65才以上に到達の者、HDCP24まで</li>\n<li>グランドシニア杯：本年中に70才以上に到達の者</li>\n<li>チャンピオン杯：前年度チャンピオン杯・忘年杯優勝者及び、本年度倶楽部競技優勝者</li>\n<li>上記以外の競技：男子HDCP 30まで、女子HDCP 35まで</li>\n</ul>\n\n※男子HDCP 31以上はHDCP 30として参加することができる。\n女子HDCP 36以上はHDCP 35として参加することができる。"
        },
        {
          title: "競技受付期間",
          content: "<div class='club-rule-sub'>9. 競技受付開始・締切は下記の通りとする。</div>\n\n<table class='club-rule-table'>\n<thead><tr><th>競技名</th><th>受付開始日</th><th>受付締切日</th><th>受付台帳記名</th></tr></thead>\n<tbody>\n<tr><td>スクラッチ競技</td><td>2ヶ月前同日</td><td>競技日10日前</td><td>本人記名</td></tr>\n<tr><td>クラブ選手権</td><td>2ヶ月前同日</td><td>競技日10日前</td><td>本人記名</td></tr>\n<tr><td>キャプテン杯</td><td>2ヶ月前同日</td><td>競技日10日前</td><td>本人記名</td></tr>\n<tr><td>理事長杯</td><td>2ヶ月前同日</td><td>競技日10日前</td><td>本人記名</td></tr>\n<tr><td>シニア選手権</td><td>2ヶ月前同日</td><td>競技日10日前</td><td>本人記名</td></tr>\n<tr><td>ミッドシニア杯</td><td>2ヶ月前同日</td><td>競技日10日前</td><td>本人記名</td></tr>\n<tr><td>グランドシニア杯</td><td>2ヶ月前同日</td><td>競技日10日前</td><td>本人記名</td></tr>\n<tr><td>上記以外の競技</td><td>1ヶ月前同日</td><td>競技日10日前</td><td>本人記名・電話受付</td></tr>\n</tbody>\n</table>"
        },
        {
          title: "エントリー・キャンセル",
          content: "※2024年1月1日より「上記以外の競技」は10日前17時エントリー締切り組数確定後、キャンセル等により空きがある場合、先着順にてエントリーを受け付ける。\n空きがない場合はキャンセル待ちとし順に案内する。\n※チャンピオン杯への参加については倶楽部より連絡を行う。\n※予定人数を超えた場合は、キャンセル待ちにて受け付ける。\n※組合せは、HPにて発表する。\n申し込み締切日までにスコアカードが規定枚数(附記-5)に満たない場合、出場は認められない。\n申込締切後参加を取消した場合、参加料を徴収する(参加資格を喪失し出場できなかった場合も含む)。尚、組合せ及びスタート時刻は委員が決定する。\n\n<div class='club-rule-sub'>10.</div>\n競技参加者はすべてスタートの10分前までに競技委員会の定める場所(カード配布場所)に到着しなければならない。カード配布時不在の場合は、ストロークプレーでは罰打2を付加とし、マッチプレーでは第1ホールの負けとする。但し、競技委員が認めた場合はこの限りではない。\n\n<div class='club-rule-sub'>11.</div>\n9項記載の競技について申込締切後、無断で競技を欠場した場合、次回の同一競技の出場資格失う。祝日杯、土曜杯、平日杯については、当該競技の次に開催される祝日杯、土曜杯、平日杯の出場資格を失う。尚、マッチプレー競技に関しては組合せが決定した後の欠場は原則として次回の同一競技への出場資格を失う。\n\n<div class='club-rule-sub'>12.</div>\n平日に行われる競技は各種会員が参加できる。\n\n<div class='club-rule-sub'>13.</div>\n競技中の練習は禁止とする。ただし18H競技の時は、ハーフ終了時の練習は、指定パッティンググリーンに於けるパッティング練習のみとする。\nマッチプレーに於いてコンシード後、グリーン上のホールアウトに向かうパッティングは練習ではない。\n\n<div class='club-rule-sub'>14.</div>\n競技委員会は、プレーヤーの行動規範（ゴルフ規則1.2b）を判断することが出来る。この規範の基準に反する重大な非行をしたプレーヤーに罰（1打罰・一般の罰・失格）を課すことが出来る。"
        },
        {
          title: "ストローク競技・マッチプレー",
          content: "<div class='club-rule-sub'>5. ストローク競技は通常次の条項のもとに行うものとし、これに反すればいずれも失格とする。</div>\n\nイ．組合わせは1組3名以上の競技参加者によることを原則とし、その場合はHDCP90を越えてはならない。但し競技委員が認めた場合はこの限りではない。\n\nロ．競技参加者は各18H終了毎に直ちに同伴競技者によって正しくアテストされ、かつ自署した各自のカードを提出しなければならない。\n\n<div class='club-rule-sub'>6. マッチプレー競技は通常次の条項のもとに行う。</div>\n競技がタイとなった場合は、何れかが1upを得るまで競技を続行する。但し、HDCPを附する競技に於けるHDCPホールは、前ラウンドと同じホールとする。\n\n<div class='club-rule-sub'>7.</div>\nマッチプレーの場合は、双方のHDCPの差の4分の3とする。"
        },
        {
          title: "附規（スロープレー・乗用カート他）",
          content: "<div class='club-rule-sub'>附規 7.</div>\nハンディキャップ競技でマッチングスコアカード方式を用いる場合は、マッチングするホール数に応じてフルハンディキャップの割合をHDCPとする。\n\n<div class='club-rule-sub'>附規 8.</div>\n各種競技において、9H終了時に2時間10分を超え更に前組と18分以上空けた場合は、その時点でハーフ最後のホールに全員に罰打2を附加する。\n\n<div class='club-rule-sub'>附規 9. 乗用カート</div>\n競技会に於いて乗用カートに乗車が認められない競技は下記の競技会とする。\nイ．スクラッチ競技、クラブ選手権。但し、プレー終了後は乗車可とする。\n※気象状況により乗車可とする場合がある。\n\nロ．乗用カートに乗車が認められていない競技でも次の場合には乗車が出来る。\n<ul>\n<li>（1）打ち直し時の往復</li>\n<li>（2）緊急時の往復</li>\n<li>（3）スカイレーターが設置されているコース間</li>\n<li>（4）競技委員の判断により乗車可とする場合</li>\n</ul>\nハ．乗用カートに乗車し移動した場合、罰打2を附加する。複数回乗車した場合は失格とする。但し、停車中の乗用カートへの乗車は可とする。\n\n<div class='club-rule-sub'>附規 10.</div>\n各種競技に於いて、競技委員がやむを得ない事情により競技委員を出来ない場合は、事務局が競技委員を代行する。\n\n<div class='club-rule-sub'>附規 11.</div>\n最大スコア（ゴルフ規則21.2）は採用せず、実際のスコアを採用する。\n\n<div class='club-rule-sub'>附規 12.</div>\n距離計測機器は高低差を計測すること、プレーヤーの球の位置に基づき、推奨されるプレーの線やクラブの選択に関する情報を得る機能をオフにした状態にて使用することが出来る。"
        },
        {
          title: "ローカルルール",
          content: "1. コースの境界は白杭、修理地は白線と青杭、ペナルティエリアは赤線又は赤杭をもってその限界を示す。\n\n2. 樹木保護の巻物などは樹木の一部とみなす。但し巻物に挟まった球が自己の球と確認出来た場合、もしくは合理的に判断出来る場合は罰無しにその真下の地点から1クラブレングス以内でホールに近づかない場所にドロップすることが出来る。\n\n3. 修理地による障害はゴルフ規則16.1aによる救済を受けなければならない。\n\n4. 指定練習場（＊ドライビングレンジ・アプローチ練習場・チップショット練習場・練習グリーン）以外での練習をしてはならない。\n\n5. 目的外グリーンのカラーは目的外グリーンの一部としゴルフ規則13.1fによる救済を受けなければならない。\n\n6. カート路（軌道間を含む全幅）に球が止まった場合はゴルフ規則16.1bによる救済を受けなければならない。\n\n7. 全ての動かせない人工物は、動かせない障害物扱いとする。（＊ヤード杭は動かせる障害物とする）\n\n8. グリーンとカラーの境に管理作業上出来る凹根切り部分は、異常なコース状態による障害としゴルフ規則16.1dによる救済を受ける事が出来る。\n\n9. 東1番ホールグリーン奥フェンスを越えたボールは全てOBとする。\n\n10. 東15番ホールに於いて、カート路（白線内）に球が止まった場合、ドロップエリアへ罰無しにドロップしなければならない。（※ドロップエリア：赤色のマークより後方へ1クラブレングス以内の長方形の区域）\n\n11. 上記以外は全てJ.G.Aのゴルフ規則による。\n\n12. 本規則は2019年1月1日より実施する。"
        },
        {
          title: "附則（参加料・スコアカード）",
          content: "<div class='club-rule-sub'>15.</div>\nローカル・ルールの追加及び変更は競技委員会掲示板にて告示する。\n\n<div class='club-rule-sub'>16.</div>\n本則及びローカル・ルールに規定のない事項はすべてJ.G.Aの競技規則による。\n\n<div class='club-rule-sub'>17.</div>\n本規則は2025年1月1日より実施する。\n\n<div class='club-rule-sub'>附規</div>\n\n<div class='club-rule-sub'>1.</div>\n競技当日のスタートは競技参加者を優先し、コース途中の先行権を有する。\n\n<div class='club-rule-sub'>2.</div>\n18Hの競技に限り、9H終了後次のスタートまでを限度として、クラブハウス内にて食事をすることが出来る。\n\n<div class='club-rule-sub'>3.</div>\n各種競技の競技方式、及び入賞範囲は、競技日程表の通りとする。\n\n<div class='club-rule-sub'>4. 競技参加料を次の通り定める。（税別）</div>\n<table class='club-rule-table'>\n<thead><tr><th>競技名</th><th>参加料</th></tr></thead>\n<tbody>\n<tr><td>クラブ選手権</td><td>3,000円</td></tr>\n<tr><td>シニア選手権</td><td>3,000円</td></tr>\n<tr><td>理事長杯</td><td>3,000円</td></tr>\n<tr><td>キャプテン杯</td><td>3,000円</td></tr>\n<tr><td>スクラッチ競技</td><td>3,000円</td></tr>\n<tr><td>グランドシニア杯</td><td>3,000円</td></tr>\n<tr><td>ミッドシニア杯</td><td>1,500円</td></tr>\n<tr><td>その他の競技</td><td>1,500円</td></tr>\n</tbody>\n</table>\n\nなお、競技参加料は競技開催日の7日前より支払い義務が発生することとする。\n\n<div class='club-rule-sub'>5. スコアカードの提出</div>\n競技会に於いては、競技申込締切日の過去2ヵ月以内にアテストされた当倶楽部のスコアカード2枚以上の提出なき場合は出場資格はない。但し、競技会のスコアカード1枚は3ヵ月有効とする。\n［参考］1月の一般スコアカードは3月末まで有効。1月の競技会のスコアカードは4月末迄有効。\n\n<div class='club-rule-sub'>6.</div>\nスクラッチ競技予選に於いて、1Rの通過ラインを89ストロークまでとし、90ストローク以上の者は2R目の出場はできない。"
        }
      ]
    },
    {
      id: "handicap",
      icon: "🏷️",
      title: "ハンディキャップ規定",
      items: [
        {
          title: "HDCP算出方法",
          content: "鶴舞カントリー倶楽部（以下TCC）は公益財団法人日本ゴルフ協会（以下JGA）のハンディキャップ規定をもとに以下の通りTCC/HDCP規定を制定する。\n\n<div class='club-rule-sub'>1. HDCPの算出</div>\nイ. JGAHDCPを参考とし、ハンディキャップ委員会（以下HC）により決定される。\nロ. 当倶楽部でのSCのみが有効とされる。\nハ. テストラウンドは4名1組にて行い、使用ティーは委員会が指定する。\n\n<div class='club-rule-sub'>2. SCの有効期限について</div>\nイ. SCの有効期限は原則なし。\nロ. ただし当倶楽部のSCのみが有効とされる。\n\n<div class='club-rule-sub'>3. 宣言制度</div>\n当日自身のプレーのSCのみが採用される。提出されたSCのみが有効とされる。\n\n<div class='club-rule-sub'>4. HDCPの発効</div>\nHDCP発効は毎月1日とし、7月1日のJGAHDCPインデックス（SC20のうちベスト8のディファレンシャルの平均）にて算出。8月1日以降も同HDCP有効とし、原則として直近のJGAHDCPインデックス（N.I）とし、TCC/HDCPの変更はN.Iの変動による。\n\n（HDCPが0〜9のTCC/HDCPはN.Iとする。）\n（HDCPが9以上のTCC/HDCPの変更はN.Iに基づく。）\n\n倶楽部はJGAHDCPの改正に基づきTCC/HDCPの変更を行う。JGAHDCPが5以上の変更の場合は速やかに変更する。TCC/HDCPの変更基準は別途定める。"
        },
        {
          title: "HDCP査定条件",
          content: "<div class='club-rule-sub'>HDCPが下がる場合</div>\n<table class='club-rule-table'>\n<thead><tr><th>鶴舞CC/HDCP</th><th>JGA HDCPとの差 4.1〜8.0</th><th>JGA HDCPとの差 8.1〜</th></tr></thead>\n<tbody>\n<tr><td>0〜9</td><td>＋1</td><td>＋2</td></tr>\n<tr><td>10〜40</td><td>＋2</td><td>＋3</td></tr>\n</tbody>\n</table>\n\n尚、HDCPは四捨五入により整数とする。\n\n<div class='club-rule-sub'>ロ. 競技入賞者及びマンスリースコア者は別途定める規定に</div>\nよりその都度見直しを実施する。\n\n<div class='club-rule-sub'>5. HDCP新規取得</div>\n提出されたSC10枚のうちベストディファレンシャル5枚にて算出する。\n\nイ. 提出されたSC5枚のうちベストディファレンシャル3枚と他倶楽部のHDCPを参考に査定する場合がある。\n\nロ. 参考ラウンドを実施する場合がある。\n\nハ. シングルHDCPを取得しようとする者に対してはその技量、マナー等別途査定を実施する。\n\n<div class='club-rule-sub'>6. HDCPを下げる場合の条件</div>\n<ul>\n<li>イ. 加齢理由による場合：申請時満60歳以上、TCC のSC3枚以上の提出。</li>\n<li>ロ. 病気理由による場合：医師の診断書、TCC のSC3枚以上の提出。</li>\n<li>ハ. 能力低下理由による場合：TCC のSC3枚以上の提出。</li>\n</ul>\n\n注1. 上記のSC3枚は申請時過去6ヵ月以内のものとする。\n注2. 改定は1年1回限りとする。但し70歳以上は2回まで。\n\n<div class='club-rule-sub'>HDCP別査定数値</div>\n<table class='club-rule-table'>\n<thead><tr><th>HDCP区分</th><th>査定値</th></tr></thead>\n<tbody>\n<tr><td>0〜5</td><td>＋2以内</td></tr>\n<tr><td>6〜9</td><td>＋3以内</td></tr>\n<tr><td>10〜20</td><td>＋4以内</td></tr>\n<tr><td>21以上</td><td>＋5以内</td></tr>\n</tbody>\n</table>\n\n<div class='club-rule-sub'>7. HDCP失効の要件</div>\n過去2年間にSC提出がない場合、HDCPは失効する。再取得は2枚以上のSC提出が必要（提出されたSC5枚のうちベストディファレンシャル3枚を参考に算出）。\n\n<div class='club-rule-sub'>8. その他</div>\n本規定に定めない事項は委員会が決定する。"
        },
        {
          title: "コースレート・スロープレート",
          content: "<div class='club-rule-sub'>男性</div>\n<table class='club-rule-table'>\n<thead><tr><th>コース</th><th>ティー</th><th>Rating</th><th>Slope</th></tr></thead>\n<tbody>\n<tr><td rowspan='6'>東</td><td>OLD Back</td><td>72.9</td><td>134</td></tr>\n<tr><td>OLD Regular</td><td>70.3</td><td>129</td></tr>\n<tr><td>OLD Front</td><td>67.0</td><td>123</td></tr>\n<tr><td>NEW Back</td><td>73.1</td><td>134</td></tr>\n<tr><td>NEW Regular</td><td>70.5</td><td>129</td></tr>\n<tr><td>NEW Front</td><td>67.2</td><td>123</td></tr>\n<tr><td rowspan='6'>西</td><td>OLD Back</td><td>72.8</td><td>128</td></tr>\n<tr><td>OLD Regular</td><td>70.2</td><td>122</td></tr>\n<tr><td>OLD Front</td><td>66.5</td><td>114</td></tr>\n<tr><td>NEW Back</td><td>73.2</td><td>131</td></tr>\n<tr><td>NEW Regular</td><td>70.5</td><td>125</td></tr>\n<tr><td>NEW Front</td><td>66.8</td><td>117</td></tr>\n</tbody>\n</table>\n\n<div class='club-rule-sub'>女性</div>\n<table class='club-rule-table'>\n<thead><tr><th>コース</th><th>ティー</th><th>Rating</th><th>Slope</th></tr></thead>\n<tbody>\n<tr><td rowspan='6'>東</td><td>OLD Back</td><td>79.4</td><td>143</td></tr>\n<tr><td>OLD Regular</td><td>76.3</td><td>136</td></tr>\n<tr><td>OLD Front</td><td>72.3</td><td>128</td></tr>\n<tr><td>NEW Back</td><td>79.6</td><td>142</td></tr>\n<tr><td>NEW Regular</td><td>76.4</td><td>135</td></tr>\n<tr><td>NEW Front</td><td>72.4</td><td>126</td></tr>\n<tr><td rowspan='6'>西</td><td>OLD Back</td><td>79.2</td><td>137</td></tr>\n<tr><td>OLD Regular</td><td>76.0</td><td>130</td></tr>\n<tr><td>OLD Front</td><td>71.4</td><td>120</td></tr>\n<tr><td>NEW Back</td><td>79.5</td><td>136</td></tr>\n<tr><td>NEW Regular</td><td>76.2</td><td>129</td></tr>\n<tr><td>NEW Front</td><td>71.6</td><td>120</td></tr>\n</tbody>\n</table>\n\n2016年9月査定"
        }
      ]
    },
    {
      id: "schedule",
      icon: "📅",
      title: "競技日程一覧（2026年）",
      items: [
        {
          title: "1月〜2月",
          content: "<div class='club-rule-sub'>1月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>1(木)</span> 新年杯 18S（西）</li>\n<li><span class='sch-date'>2(金)</span> 月例杯 18S（西）</li>\n<li><span class='sch-date'>4(日)</span> 月例杯 18S（Bクラス）（西）</li>\n<li><span class='sch-date'>11(日)</span> 月例杯 18S（Aクラス）（西）</li>\n<li><span class='sch-date'>18(日)</span> 研修会（西）</li>\n<li><span class='sch-date'>25(日)</span> シニア研修会（西）</li>\n</ul>\n\n<div class='club-rule-sub'>2月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>1(日)</span> 月例杯 18S（オープン）（東）第1ブロック</li>\n<li><span class='sch-date'>15(日)</span> 月例杯 18S（オープン）（東）第2ブロック</li>\n<li><span class='sch-date'>17(火)</span> ポイントターニー杯 18S（東）</li>\n<li><span class='sch-date'>21(土)</span> 研修会（東）・女子研修会（東）</li>\n<li><span class='sch-date'>22(日)</span> シニア研修会（東）</li>\n<li><span class='sch-date'>25(水)</span> 月例杯（東）</li>\n</ul>"
        },
        {
          title: "3月〜4月",
          content: "<div class='club-rule-sub'>3月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>1(日)</span> 月例杯 18S（Bクラス）・女子研修会（東）</li>\n<li><span class='sch-date'>8(日)</span> 研修会 27S（Bクラス）・女子研修会（東）</li>\n<li><span class='sch-date'>15(日)</span> スクラッチ競技予選 36S（東）</li>\n<li><span class='sch-date'>  </span> HDCP 10迄 上位20位選出</li>\n<li><span class='sch-date'>  </span> （但し予選 1R 89S迄を通過ラインとし90S以上は</li>\n<li><span class='sch-date'>  </span> 2Rに出場できない）</li>\n<li><span class='sch-date'>22(日)</span> スクラッチ競技決勝 36S（72S通算）（西）</li>\n<li><span class='sch-date'>  </span> 月例杯 18S（Aクラス）（西）</li>\n<li><span class='sch-date'>26(木)</span> グランドシニア杯 予選 18S（西）</li>\n<li><span class='sch-date'>  </span> 本年中に70才以上に到達する者</li>\n<li><span class='sch-date'>  </span> 上位16名選出 クオリファイ賞</li>\n<li><span class='sch-date'>29(日)</span> 桜花杯 18S（各種名選）（西）</li>\n<li><span class='sch-date'>31(火)</span> グランドシニア杯（各種委員賞）（西）</li>\n</ul>\n\n<div class='club-rule-sub'>4月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>4(土)</span> 土曜杯 18S（東）</li>\n<li><span class='sch-date'>5(日)</span> グランドシニア杯1回戦 18M（東）</li>\n<li><span class='sch-date'>  </span> 月例杯 18S（オープン）（東）第1ブロック</li>\n<li><span class='sch-date'>7(火)</span> グランドシニア杯2回戦 各18M（東）</li>\n<li><span class='sch-date'>12(日)</span> グランドシニア杯準決勝 各18M（西）</li>\n<li><span class='sch-date'>14(火)</span> グランドシニア杯決勝 各18M（西）</li>\n<li><span class='sch-date'>19(日)</span> 月例杯 18S（オープン）（東）第2ブロック</li>\n<li><span class='sch-date'>26(日)</span> 月例杯 18S（東）</li>\n</ul>"
        },
        {
          title: "5月〜6月",
          content: "<div class='club-rule-sub'>5月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>3(日)</span> 研修会（西）</li>\n<li><span class='sch-date'>5(火)</span> ファミリー大会 ※非競技</li>\n<li><span class='sch-date'>6(水)</span> キャプテン杯 予選 18S（西）</li>\n<li><span class='sch-date'>10(日)</span> HDCP 24迄 上位32名選出（西）</li>\n<li><span class='sch-date'>  </span> キャプテン杯 決勝32名 18S（36S通算）（西）</li>\n<li><span class='sch-date'>17(日)</span> 月例杯 18S（Aクラス）（西）</li>\n<li><span class='sch-date'>20(水)</span> 関東女子倶楽部対抗 主催競技（西）</li>\n<li><span class='sch-date'>24(日)</span> シニア研修会（西）</li>\n<li><span class='sch-date'>  </span> 女子研修会</li>\n<li><span class='sch-date'>25(月)</span> 関東女子倶楽部対抗 主催競技</li>\n<li><span class='sch-date'>  </span> 関東女子倶楽部主催 予選</li>\n<li><span class='sch-date'>31(日)</span> 理事長杯 1次予選 18S（西）</li>\n<li><span class='sch-date'>  </span> HDCP 24迄 上位60名選出 クオリファイ賞</li>\n</ul>\n\n<div class='club-rule-sub'>6月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>7(日)</span> 理事長杯 2次予選 18S（西）上位32名選出</li>\n<li><span class='sch-date'>  </span> 関東ゴルフ連盟 主催競技</li>\n<li><span class='sch-date'>9(火)</span> 関東倶楽部対抗 主催競技</li>\n<li><span class='sch-date'>14(日)</span> 理事長杯 1・2回戦 各18M（西）</li>\n<li><span class='sch-date'>15(月)</span> 月例杯 18S（Bクラス）（西）</li>\n<li><span class='sch-date'>  </span> 関東ゴルフ連盟 主催競技</li>\n<li><span class='sch-date'>21(日)</span> 理事長杯 3回戦・準決勝（予備日）各18M（西）</li>\n<li><span class='sch-date'>  </span> 月例杯 18S（Aクラス）（西）</li>\n<li><span class='sch-date'>28(日)</span> 理事長杯 決勝 36M（西）</li>\n<li><span class='sch-date'>  </span> 女子研修会（西）</li>\n</ul>"
        },
        {
          title: "7月〜8月",
          content: "<div class='club-rule-sub'>7月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>4(土)</span> 土曜杯 18S（東）</li>\n<li><span class='sch-date'>5(日)</span> 月例杯 18S（東）</li>\n<li><span class='sch-date'>12(日)</span> 研修会（東）</li>\n<li><span class='sch-date'>19(日)</span> 月例杯 18S（Aクラス）（東）</li>\n<li><span class='sch-date'>26(日)</span> シニア研修会（東）</li>\n</ul>\n\n<div class='club-rule-sub'>8月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>2(日)</span> 研修会（西）</li>\n<li><span class='sch-date'>9(日)</span> 女子研修会（西）</li>\n<li><span class='sch-date'>  </span> 月例杯 18S（オープン）（西）第1ブロック</li>\n<li><span class='sch-date'>22(土)</span> 女子研修会（西）</li>\n<li><span class='sch-date'>23(日)</span> シニア研修会（西）</li>\n<li><span class='sch-date'>30(日)</span> 月例杯 18S（西）</li>\n</ul>"
        },
        {
          title: "9月〜10月",
          content: "<div class='club-rule-sub'>9月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>6(日)</span> 研修会 27S（東）</li>\n<li><span class='sch-date'>  </span> 女子研修会</li>\n<li><span class='sch-date'>13(日)</span> クラブ選手権 予選 18S（東）</li>\n<li><span class='sch-date'>  </span> HDCP 10迄</li>\n<li><span class='sch-date'>20(日)</span> クラブ選手権 予選 18S（東）</li>\n<li><span class='sch-date'>  </span> 予選第1ラウンドで上位32名まで第2ラウンド進出</li>\n<li><span class='sch-date'>  </span> 第1と第2の合計で上位16名決勝進出</li>\n<li><span class='sch-date'>22(火)</span> クラブ選手権 メダリスト・クオリファイ賞（東）</li>\n<li><span class='sch-date'>  </span> 月例杯 18S（Bクラス）（東）</li>\n<li><span class='sch-date'>27(日)</span> クラブ選手権 1・2回戦 各18M（東）</li>\n<li><span class='sch-date'>  </span> 月例杯 18S（Aクラス）（東）</li>\n</ul>\n\n<div class='club-rule-sub'>10月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>3(土)</span> シニア研修会（西）</li>\n<li><span class='sch-date'>4(日)</span> クラブ選手権 準決勝 36M（東）</li>\n<li><span class='sch-date'>  </span> 月例杯 18S（Bクラス）（東）</li>\n<li><span class='sch-date'>11(日)</span> クラブ選手権 決勝 36M（東）</li>\n<li><span class='sch-date'>  </span> 研修会（東）</li>\n<li><span class='sch-date'>12(月)</span> 女子研修会</li>\n<li><span class='sch-date'>18(日)</span> シニア選手権 予選 18S（東/西）※非競技</li>\n<li><span class='sch-date'>  </span> （本年中に55才以上に到達する者）</li>\n<li><span class='sch-date'>  </span> HDCP 24迄 スクラッチにより上位32名選出</li>\n<li><span class='sch-date'>25(日)</span> シニア選手権 1・2回戦 各18M（西）</li>\n<li><span class='sch-date'>  </span> 月例杯 18S（Aクラス）（西）</li>\n</ul>"
        },
        {
          title: "11月〜12月",
          content: "<div class='club-rule-sub'>11月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>1(日)</span> シニア選手権 3回戦・準決勝 各18M（西）</li>\n<li><span class='sch-date'>  </span> 月例杯 18S（オープン）（西）第1ブロック</li>\n<li><span class='sch-date'>3(火)</span> 文化の日杯 18S（オープン）（西）</li>\n<li><span class='sch-date'>8(日)</span> シニア選手権 決勝 27M（西）</li>\n<li><span class='sch-date'>  </span> 研修会・女子研修会（西）</li>\n<li><span class='sch-date'>15(日)</span> 月例杯 18S（オープン）（西）第2ブロック</li>\n<li><span class='sch-date'>21(土)</span> 紅葉杯（各種名選）18S（東）</li>\n<li><span class='sch-date'>22(日)</span> ミッドシニア杯 予選 18S（東）</li>\n<li><span class='sch-date'>  </span> （本年中に65才以上に到達する者）（36S通算）</li>\n<li><span class='sch-date'>  </span> HDCP 24迄 上位16名選出 クオリファイ賞</li>\n<li><span class='sch-date'>29(日)</span> ミッドシニア杯 決勝 18S（東）</li>\n</ul>\n\n<div class='club-rule-sub'>12月</div>\n<ul class='schedule-list'>\n<li><span class='sch-date'>6(日)</span> 研修会（東）・女子研修会（東）・シニア研修会（西）</li>\n<li><span class='sch-date'>12(土)</span> 土曜杯 18S（東）</li>\n<li><span class='sch-date'>13(日)</span> 月例杯 18S（Bクラス）（東）</li>\n<li><span class='sch-date'>20(日)</span> 月例杯 18S（Aクラス）（東）</li>\n<li><span class='sch-date'>27(日)</span> 2026チャンピオン杯 18S（東）</li>\n<li><span class='sch-date'>  </span> （本年度優勝者のみ）</li>\n<li><span class='sch-date'>  </span> 忘年杯 18S（東）</li>\n<li><span class='sch-date'>31(水)</span> 特別営業日</li>\n</ul>"
        }
      ]
    }
  ]
};
